### ISSUE TITLE
surprising good reproduced results

### ISSUE THREAD

**Issue by lihenglin** [cjshui/WAAL#1]
Hi, 

I recently reproduced your code and found out that the results I got on CIFAR10 is much better than the reported numbers in your paper. (80.97% accuracy with 6K labels)
Is there any discrepancy between the released code and the way you obtained the results in your paper since I don't think it is a reasonable fluctuation? (The standard deviation on CIFAR10 with 6K labels is only 0.60%.)

Thanks.

**Comment by cjshui** [comment]
Hi,
Yes, there is a discrepancy between the released code and the results in the paper. 
In the paper, we did not adopt the data-augmentation approach, while the released code added several data-augmentation. 
Intuitively, adding augmentation can improve the prediction performance particularly in the limited-labelled scenarios (such as AL, the labelled datasets are always limited)...

**Comment by lihenglin** [comment]
Got it. Thanks for your quick reply.
