### ISSUE TITLE
Some implementation issues

### ISSUE THREAD

**Issue by abababa-ai** [cjshui/WAAL#2]
I have the following questions and would like to know more about them
1. A previous issue said that additional data augmentation can significantly improve performance, is it possible to remove data augmentation to get the experimental results described in the paper?
2. It seems that the learning rate does not decay after 75% epoch?
3. Where is the implementation of the code corresponding to the selection and mixture coefficients?

Looking forward to your reply！

**Comment by cjshui** [comment]
Thanks for your questions. Sorry for the late responses
1. I think so. Removing the data augmentation can effectively reduce the performance.
2. I am not 100% sure of this question. I guess it does not make a big difference.  
3. I think it is all in the code. Specifically, in the following link
https://github.com/cjshui/WAAL/blob/7104bc0113e7e73218a6d287951642a76d8005df/query_strategies/wasserstein_adversarial.py#L342
