### ISSUE TITLE
What should be the length of the datahandler?

### ISSUE THREAD

**Issue by MoonLab-YH** [cjshui/WAAL#3]
Hi, thank you first for sharing your amazing work.

I'm currently looking through datahandler in dataset_WA.py,

and I found that length of the datahandler is defined as: **max**(len(self.X1),len(self.X2))

However, at the same time, there was a comment which reads:

\# returning the minimum length of two data sets.

According to the comment, I guess the length of the datahandler should be:  **min**(len(self.X1),len(self.X2))

Could you tell me which is the correct definition for the length?

I attach the definition of the __len__() method below:

    def __len__(self):

        # returning the minimum length of two data-sets

        return max(len(self.X1),len(self.X2))

**Comment by cjshui** [comment]
Hi, I think the Len should be the max rather than min. There is a typo in the description. Because we adopted resampling for the smaller dataset.

**Comment by MoonLab-YH** [comment]
Thank you for quick reply!
